{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: weather-db
spec:
  type: LoadBalancer
  {{- with .Values.db.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: weather-db
{{- end }}
