# gitops/values/eks-a/cloudflared-values.yaml
replicaCount: 1 # 평상시 Cold Standby 상태로 터널 비활성화 (DR Failover 발생 시 1로 승격)
tunnelId: "6be45600-f095-4844-b7d5-98dd51777dc9"
credentialsSecret: "cloudflared-creds"
ingress:
  - hostname: "infrastudy.store"
    service: http://gateway-service.jit-hub.svc.cluster.local:80