# gitops/values/eks-a/ops-values.yaml
keda:
  enabled: true
  minReplicaCount: 3
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        metricName: http_requests_total
        query: sum(rate(http_requests_total[2m]))
        threshold: '50'
karpenter:
  enabled: true
  nodePoolName: eks-a-nodepool
customScheduler:
  enabled: true 
