# On-Prem 클러스터 전용 Override Values
# Umbrella Chart (Subchart) 구조에 맞게 작성

ingressRule:
  namespace: "jit-hub"
  #host: "ccmall.shop"
  host: "infrastudy.store"

gateway:
  replicaCount: 1
  image:
    #repository: "harbor.ccmall.shop/jit-hub/jit-hub-gateway"
    #tag: "seed"
    #repository: "172.16.8.200:8888/jit-hub/jit-hub-gateway"
    repository: "harbor.infrastudy.store/jit-hub/jit-hub-gateway"
    tag: "v1"

auth:
  replicaCount: 1
  image:
    #repository: "harbor.ccmall.shop/jit-hub/auth-service"
    #tag: "seed"
    #repository: "172.16.8.200:8888/jit-hub/auth-service"
    repository: "harbor.infrastudy.store/jit-hub/auth-service"
    tag: "v1"    
  db:
    enabled: true
    loadBalancerIP: "172.16.8.47"
    host: "auth-db"
    persistence:
      enabled: true
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-authdb"

weather:
  replicaCount: 1
  image:
    #repository: "harbor.ccmall.shop/jit-hub/weather-service"
    #tag: "seed"
    #repository: "172.16.8.200:8888/jit-hub/weather-service"
    repository: "harbor.infrastudy.store/jit-hub/weather-service"
    tag: "v1"
  db:
    enabled: true
    loadBalancerIP: "172.16.8.48"
    host: "weather-db"
    persistence:
      enabled: true
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-weatherdb"

traffic:
  replicaCount: 1
  image:
    #repository: "harbor.ccmall.shop/jit-hub/traffic-service"
    #tag: "seed"
    #repository: "172.16.8.200:8888/jit-hub/traffic-service"
    repository: "harbor.infrastudy.store/jit-hub/traffic-service"
    tag: "v1"
  db:
    enabled: true
    loadBalancerIP: "172.16.8.49"
    host: "traffic-db"
    persistence:
      enabled: true
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-trafficdb"

tourist:
  replicaCount: 1
  image:
    #repository: "harbor.ccmall.shop/jit-hub/tourist-service"
    #tag: "seed"
    #repository: "172.16.8.200:8888/jit-hub/tourist-service"
    repository: "harbor.infrastudy.store/jit-hub/tourist-service"
    tag: "v1"
  db:
    enabled: true
    loadBalancerIP: "172.16.8.50"
    host: "tourist-db"
    persistence:
      enabled: true
      size: 100Mi
      nfs:
        server: "172.16.8.203"
        path: "/nfs/shared/jithub-touristdb"
