apiVersion: v1
kind: Secret
metadata:
  name: cluster-eks-a
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    # ApplicationSet 및 템플릿 매핑을 위한 커스텀 레이블
    environment: eks-a
    cloud-provider: aws
    status: active
type: Opaque
stringData:
  name: eks-a
  server: https://<AWS-EKS-A-API-SERVER-ENDPOINT>
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "eks-a",
        "roleARN": "arn:aws:iam::<AWS-ACCOUNT-ID>:role/<ARGOCD-ACCESS-ROLE>"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<BASE64-ENCODED-CA-DATA>"
      }
    }
