apiVersion: v1
kind: Secret
metadata:
  name: cluster-onprem
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    # ApplicationSet 및 템플릿 매핑을 위한 커스텀 레이블
    environment: onprem
    cloud-provider: baremetal
    status: active-standby
type: Opaque
stringData:
  name: onprem
  # ArgoCD가 온프레미스 내부
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": true
      }
    }
